### ISSUE TITLE
Use .strip () function on username parsing process

### ISSUE THREAD

**Issue by deavmi** [pjuu/pjuu#102]
Use .strip () function on username parsing process

**Comment by docapotamus** [comment]
Good idea. There can't be any harm in the username. Will see what OWASP says about passwords because it could work there also. :+1:

**Comment by mcrmonkey** [comment]
Indeed
However, other than general escaping etc the password shouldn't be messed with.

**Comment by deavmi** [comment]
Of course. The password should be able to contain spaces.

**Comment by deavmi** [comment]
Don't use it for passwords. I want spaces in my password. :) lol

**Comment by docapotamus** [comment]
You are correct on that but strip only removed surrounding spaces. Would be confusing if we removed any though. Will implement this when I get back.

**Comment by deavmi** [comment]
Oh yes. I see what you mean. Maybe do a .split(" ") and then iterate through that list and concatenation to a string. And then use that as the restitched username. That should work. Idk I think this is right. Yeah this will work.

**Comment by docapotamus** [comment]
The username doesn't matter because it had to match a regex otherwise it fails anyway.

**Comment by deavmi** [comment]
I see what you mean, but it would allow for people who make tonnes of erros to logon easily, but never mind, that would cause the world to explode in to fine bits of spaces.

**Comment by deavmi** [comment]
Doing it on the password makes no sense at allI want the password `\ Hello\ \ `.
