### ISSUE TITLE
Add T&Cs to signup

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#116]
Add some T&Cs to the empty '/terms' page and ensure there is a message explaining acceptance on sign up.

Highlight in the code that `about`, `privacy policy` and `term and conditions` can be changed if you are running the software yourself. So long as the sources are available under the GPL. There is nothing wrong with version controlled legal documents! :smile:

**Comment by mcrmonkey** [comment]
Done. Just needs formatting and putting in to the site.
