### ISSUE TITLE
Not recognising "@Joe as mention or tstsgshhs@Joe

### ISSUE THREAD

**Issue by deavmi** [pjuu/pjuu#166]
More info here: https://pjuu.com/joe/a44a0854a5eb11e582c7f23c9150d009

**Comment by docapotamus** [comment]
tstsgshhs@Joe wouldn't be allowed because there has to be a delimiter before the `@`

The fix just needs making to this line: https://github.com/pjuu/pjuu/blob/master/pjuu/lib/parser.py#L55 and a test added for it.

Will get round to this soon but if any one wants to do this it should be easy :)

**Comment by deavmi** [comment]
Lekker. :smiley_cat:

**Comment by deavmi** [comment]
awesome
