### ISSUE TITLE
Image upload orientation 

### ISSUE THREAD

**Issue by mcrmonkey** [pjuu/pjuu#181]
When users upload pictures from phones to the site they can often be oriented incorrectly.
This isn't the users fault and its usually down to how the device saved the picture.

Devices can correctly orient the picture based on EXIF information contained within the image when it was saved.

We should read this info from the image and rotate the picture accordingly to it looks right.

**Comment by docapotamus** [comment]
This should be relatively easy.

Will need to add that we read the data in the exif tag to orientate the image the correct way and that we don't read any other data and remove it on save.
