### ISSUE TITLE
Avatars not showing for posts on the search page.

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#212]
This is because we are not fulling in the users avatar image from Mongo.

Should be fixed in https://github.com/pjuu/pjuu/blob/master/pjuu/users/backend.py#L197

Thanks @deavmi for the report. https://pjuu.com/deavmi/2bd92f10ed1411e58d0af23c9150d009

**Comment by deavmi** [comment]
@docapotamus Pleasure :smile:

**Comment by deavmi** [comment]
Awesome. :)
