### ISSUE TITLE
Permissions and public profiles.

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#215]
This replaces the _very old_ issue #46 which discussed permissions in Pjuu which was used to flesh out a few ideas along with some posts on https://pjuu.com.

Myself, @mcrmonkey, @mukt and @deavmi have discussed what should go in to Pjuu to allow public profiles whilst protecting privacy.

Below are the key points on how this will work:

- Allow users to assign groups to their followers. All new followers will, by default, will be added to the **Public** group which will also include the internet at large. They will only be able to see these posts if you post to **Public**. A user will be able to create multiple groups and assign a follower into any number of these groups.

- When a user posts, they will be able to decide which group the post is aimed at. Only the followers in that group will be able to see or comment on that post and will have it prepended to their feeds.

- Posts within your Public feed will be accessible to all Pjuu/internet users.

- If a user who is not a member of Pjuu visits the users profile they will be presented with the posts in the users **Public** romp.

- Comments on a post do not have their own permission rules and they inherit any rules from the parent post/user. If you comment on a protected post then only the users who can interact on that post will be able to also comment.

- If a post is tagged with multiple romps and a user appears in more than one of these they will not have the post prepended twice.

- On deleting a romp all posts which are __only__ posted to that romp along with all comments will be deleted. Any users assigned to that romp will no longer be part of it as it will no longer exist. They will however still be assigned to the **Public** romp.

- Your **About** message will become public in the process, but if you have no **Public** posts then your profile will be empty of posts to the internet and your followers.

- Non-Pjuu users **will not** be able to see your followers or following lists and *no* user will be able to see who you've assigned to what romp.

The name Romp is the collective name for a group of Otters. In case you're wondering, the Pjuu mascot __Ot__ is an Otter.

**Comment by deavmi** [comment]
What is a "Romp"?

**Comment by mcrmonkey** [comment]
Romp - a collective noun for a group of otters

**Comment by deavmi** [comment]
:heart: Awesome :)
