### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by deavmi** [pjuu/pjuu#227]
There is a spelling error on one of the pages, I think it was the CSRF token thing. If you have cookies disabled then the page comes up and I think there is a spelling error in the error description.

**Comment by docapotamus** [comment]
Set here:

https://github.com/pjuu/pjuu/blob/master/pjuu/lib/errors.py#L39-L54

Cheers @deavmi 

Pjuu will unfortunately not work with cookies disabled as we have to way to keep track of your login session.

**Comment by docapotamus** [comment]
Thanks for the fix

**Comment by deavmi** [comment]
Pleasure. :)

**Comment by deavmi** [comment]
> Pjuu will unfortunately not work with cookies disabled as we have to way to keep track of your login session.

Of course. @Joe :)
