### ISSUE TITLE
Animate GIF's

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#241]
May be nice to allow animate GIFs to be uploaded Pjuu.

**Comment by deavmi** [comment]
This would be awesome.

**Comment by docapotamus** [comment]
Good you commented on this I'm just starting work on it 😄.

I have this working but there is a problem in subsequent frames from the first. They are all distorted. It looks like this is fixable though but it may be a little rough.

I will report back in a bit.

**Comment by deavmi** [comment]
Awesome :smile:.

**Comment by docapotamus** [comment]
There is a strange issue with Pillow saving animated GIFs.

It does work but it appears to drop the pallet on all but the first frame.

http://stackoverflow.com/questions/24688802/saving-an-animated-gif-in-pillow
https://github.com/python-pillow/Pillow/issues/1355
https://github.com/python-pillow/Pillow/pull/1379
https://github.com/python-pillow/Pillow/pull/1384

**Comment by docapotamus** [comment]
Had to open an issue for this one as I am a bit lost. Just need some direction.
https://github.com/python-pillow/Pillow/issues/1976

**Comment by deavmi** [comment]
Okay.
 Sounds good then.

Any other imaging library you could use? Just asking.

On 21 June 2016 8:19:50 PM SAST, Joe Doherty <notifications@github.com> wrote:
>Had to open an issue for this one as I am a bit lost. Just need some
>direction.
>https://github.com/python-pillow/Pillow/issues/1976
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pjuu/pjuu/issues/241#issuecomment-227526792

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by docapotamus** [comment]
We could use ImageMagick and some Python bindings.

http://docs.wand-py.org/en/0.4.3/index.html

**Comment by deavmi** [comment]
Cooleo.

**Comment by deavmi** [comment]
Awesome. Did ImageMajick do the trick?

**Comment by docapotamus** [comment]
@deavmi it did yes. It's really easy to work with via python-wand.

**Comment by deavmi** [comment]
Nice. :+1: Good work btw.
