### ISSUE TITLE
Red on Green for new alerts, colour blind.

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#260]
A user has reported that the red on green when you have a new alert is very hard to see for colour blind users.

I completely forgot about this.

**Comment by mcrmonkey** [comment]
Guidance:
http://www.vischeck.com/examples/
http://colorvisiontesting.com/what%20colorblind%20people%20see.htm
http://colororacle.org/

**Comment by mcrmonkey** [comment]
some of the changes we could make for #247 could benefit these users

**Comment by buskirka** [comment]
Hey, that's me!
If you need any testing help, I can (naturally) help with red/green colorblindness...but when it comes to other forms of colorblindness I'm just as lost as anyone else.

**Comment by docapotamus** [comment]
@buskirka what would be the best colour for you over the green at the top to highlight new alerts?

**Comment by mcrmonkey** [comment]
As an option we could also adjust the icons so that we have outlines for non active things and filled in things for when they require attention.
The colour of these then shouldn't matter as much but we would maybe need to ensure that the colour of the icon is inverted in a way i.e. light background and darker coloured icon, where a dark BG gets a lighter coloured icon

The BBC do this same thing with their logo

**Comment by buskirka** [comment]
@docapotamus For me, it would probably have to be blue or white for a simple color change to work well. Using blue would help red-green colorblindness, but I think it might cause problems for those with other types of colorblindness. White utilizes simple contrast, and I think that would be visible regardless of colorblindness. (It would be for me, at least.) 

@mcrmonkey I think that would also work, assuming the contrast of the light background against the dark icon is utilized.

**Comment by johnnynull** [comment]
I haven't looked yet, but is it possible to modify the bell in another way? For instance, the "quiet " bell is low-contrast, but to alert for messages, it is both higher contrast and there's some lines coming from it, or ((( ))) s, indicating sound/action.

**Comment by docapotamus** [comment]
@johnnynull. I've looked at this there is nothing in Fontawesome which looks like this. I can add a style though which rotates it very slightly.

I could also have it so it just the outline when there is not alerts and it is solid when there is alerts.

**Comment by docapotamus** [comment]
Is this too subtle?
No alert
![No alerts](https://pjuu.com/uploads/01f36b66326511e6910f0401fe607e01.png)
New alert
![New alerts](https://pjuu.com/uploads/0d84d7a8326511e6b5570401fe607e01.png)

**Comment by buskirka** [comment]
Well, it would be an improvement for me (as in, it's still visible in alert form), but I think that might be a bit too subtle overall.

**Comment by johnnynull** [comment]
There's check marks and stuff in fontawesome. You could consider ditching the bell.
Alternatively, I looked up how to submit a request for a new font in fontawesome. I could move forward with that.
Or could it be a small png or gif? I can make those.
Or could I make fonts in fontforge (Never did it, but I can try) and you could use that?

**Comment by docapotamus** [comment]
It seems way to complex to add a new icon in to Font Awesome plus I have seen the vast majority get ignored by the team there.

The problem with the PNG is the extra load. We change it by adding/removing classes so it needs to be done in CSS.

Is there any other way of highlighting it?

@buskirka if we kept it as red as well as being tilted and solid colour are you still able to see it? I mean does the icon become invisible if its red or is just indistinguishable from it being non-red.

**Comment by johnnynull** [comment]
You make good points.

**Comment by docapotamus** [comment]
I've made this red again and added a white text glow to better help highlight it.

@mcrmonkey I accidentally pushed to master like an idiot. Luckily this feature isn't tested and code coverage hasn't dropped further since the issue with `coverage`.

Closing this issue.

@buskirka please let me know if this has helped.

Thanks for the issue.

**Comment by buskirka** [comment]
@docapotamus The red is quite impossible to recognize directly against the green. I noticed the change, however, and the bright outline helps a lot. Thanks!

**Comment by docapotamus** [comment]
@buskirka would a darker red help?
