### ISSUE TITLE
Tip box doesn't look right 

### ISSUE THREAD

**Issue by mcrmonkey** [pjuu/pjuu#272]
### Version
312f19a

### Operating system
Debian

### Expected behaviour
Under testing the Tips box doesn't look as good as it should

### Actual behaviour
The tips box should look better

### Steps to reproduce
1. Install Pjuu as per instructions in readme.md

2. Signup and activate the account

3. Login

4. Observe the tips box

### References
There are no other references at this time.

**Comment by docapotamus** [comment]
Nice one :smile:
