### ISSUE TITLE
Revover password confirms sent e-mail with no e-mail filled in

### ISSUE THREAD

**Issue by deavmi** [pjuu/pjuu#287]
On the version of Pjuu that is running at pjuu.com there is a problemo.

Go to recover password.

Don't enter an e-mail address.

Hit recover.

Then there is a message saying that an e-mail has been sent to recover your password (however no e-mail was ever entered).

**Comment by deavmi** [comment]
I have screenshots if you want.

**Comment by mcrmonkey** [comment]
Page is accepting a blank input field.

Adding a "required" to the input field would solve this in the users browser

**Comment by deavmi** [comment]
Awesome. :)

**Comment by docapotamus** [comment]
Just to confirm that an e-mail isn't sent if you do not exist. The flash message says:

"If we've found your account we've e-mailed you"

I will make it so data is required rather than empty.

**Comment by deavmi** [comment]
Awesome.


I see how that is a privacy feature. Nice work man. :)

**Comment by docapotamus** [comment]
Sorted @deavmi.

You can still put in an invalid username or email but its better if you don't put anything in.

Thanks for the bug report. Much appreciated.

**Comment by deavmi** [comment]
Pleasure :+1: Thumbs up for the fix. :)
