### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#313]
I doubt we will be moving to Python 3 ourselves any time soon but it will be worth the effort now to support Python 3.

As a Debian user 3.4 is available in Jessie so I will most likely target that at a minimum.

**Comment by docapotamus** [comment]
This is going to be a tough one.

I have changed things which need changing such as `xrange` to `builtin.range`

`print` statements to functions.

There are a load of issues with strings though.

**Comment by deavmi** [comment]
Python 2. Kill it with fire.

**Comment by deavmi** [comment]
You could branch the current working branch and slowly start translation. Idk

**Comment by deavmi** [comment]
Might want to stop new feature development and start the translation/migration to Py3 and focus on that.

**Comment by docapotamus** [comment]
Features have stopped at the moment any how as I really need to get my arse in to gear and do the Postgres migration.

May be worth doing this first. It shouldn't be too much of hassle, just a lot of small changes.

http://python-future.org/compatible_idioms.html the following guide pretty much covers it.

**Comment by deavmi** [comment]
Maybe get that last infrustructural change done and then start migration shortly afterwards

**Comment by mcrmonkey** [comment]
Closing this becuase of #346
