### ISSUE TITLE
Python 2 EOL and the future

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#346]
Python 2 comes to its end of life in [January 2020](https://pythonclock.org/)

~~I honestly do not have any interest or use for Python these days and I don't see the point in migrating it to Python 3. To that end I would like this ticket to be the official re-write topic.~~

~~Development on the project has stalled recently and this is in part to the cruft that lay around the codebase. Over the last few months I have played with the idea of rewritting it to hopefully kickstart development again.~~

~~I have investigated using both NodeJS and Go. I work with these languages in my career so this is why I looked in to them.~~

~~I would very much like to start work on V2 of Pjuu in Go, below are my reasons.~~

~~1. Fast. It compiles.~~
~~2. Go routines. I prefer this to async in Node (Promises).~~
~~3. Minimal. No need to learn all the do's and don'ts of Javascript.~~
~~4. Standard Library. Go has a very good standard library similar to Python.~~
~~5. Image processing. It comes out of the box (with the animated Gif support we need).~~
~~6. Good database drivers. For Mongo, Postgres and Redis.~~

~~Honestly, Pjuu doesn't need much else.~~

~~I am going to start down this path. Try and find good patterns to simplify development and test some assumptions.~~

Upon looking at the story when aiming at Python 3.5 (included in Debian Stretch) it's actually not too bad. I have created a branch 2to3 and have the tests passing.

There is still some work to do and a lot of testing but hopefully this shouldn't take too long.

As a side. I will try and incorporate a lot of the open issues in to this development work. This means building this around PostgreSQL and working on the migration plan from MongoDB.

If you have any other suggestions or thoughts, please, let me know.

I would also like to thank all of the users who have donated to Pjuu. Your support is much appreciated.

**Comment by mcrmonkey** [comment]
:+1: 
stuck a project here: https://github.com/pjuu/pjuu/projects/2

**Comment by docapotamus** [comment]
Thanks mate!

I was going to work out how to set up a project.

**Comment by docapotamus** [comment]
I am going to split this in to 2 seperate parts.

1. I will re-do/modernize the design in the current code base
2. I will start to port over the code to Go

**Comment by docapotamus** [comment]
We have completed the migration to Python 3. I will open other issue for the rest.
