### ISSUE TITLE
Move Docker builds

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#362]
The free Docker hub project is not very good for building images for a couple of reasons:

1. It takes for every, up to an hour to have the 3 images build.

Only pjuu/base actually has anything which would take time within it. pjuu/web and pjuu/worker simply import the base and change the entry point.

2. It builds out of order.

I have all 3 images configured but it starts building them all at the same and it is non-obvious how to change this even if I can.

So I propose moving the build to Travis-CI/Github Actions, it only takes a couple of commands and we can upload directly to Dockerhub from there.

**Comment by mcrmonkey** [comment]
:+1: 
sounds good to me 

The only downer by not having hub do the build is that the image repo on hub then lacks extra info like the readme from the main github repo and information about the builds.

**Comment by docapotamus** [comment]
@mcrmonkey I guess we can still integrate with hub, just disable any builds on there.

**Comment by mcrmonkey** [comment]
the only downer with doing that is that hub still requires full access to someones account 
Until its sorted properly I'm hesitant to use it again

**Comment by docapotamus** [comment]
@mcrmonkey going to leave this open for a short time until we know that these actions are working well

**Comment by docapotamus** [comment]
This is now working nicely
