### ISSUE TITLE
Alternative languages

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#384]
With the Refactor/AsyncIO project we are in a fortunate position.

Pjuu isn't that large a piece of software. We could easily re-write it at the same to help save further on costs.

**Comment by docapotamus** [comment]
Asyncio is a bit all over the spot in Python. When Pjuu was written Flask and Django were the two main frameworks.

If we we're to re-write there:

- Go with 2 alternatives, use `net/http` or `fasthttp` base tools. Everything is based around there.
- Rust with 3 alternatives, Actix Web, Rocket or Warp.

**Comment by docapotamus** [comment]
Other advantages include:

- Data. Pjuu calls the database a lot, even from templates. This could be reduced to just views (routes/controllers)
- Cost to run, more used per CPU resource

**Comment by sigg3** [comment]
Have you considered Starlette? 

=> https://www.starlette.io/

Not sure if it's the right use case for it :)

**Comment by docapotamus** [comment]
@sigg3, I have looked at at starlette but have no experience with it.

**Comment by docapotamus** [comment]
https://github.com/gofiber/fiber/ is very promising. It supports everything we need in a framework.

**Comment by sigg3** [comment]
Looks great! I'm strictly a python coder these days, but you Go ahead :D

**Comment by docapotamus** [comment]
@sigg3 I think this is still open, so we're not Going anywhere just yet :P

**Comment by docapotamus** [comment]
@sigg3 looks like Starlette meets all of our requirements. A lot of the code can be moved over.

Closing this. Python still seems like a great option.
