### ISSUE TITLE
requirements.txt and python version for developing

### ISSUE THREAD

**Issue by sigg3** [pjuu/pjuu#404]
No `requirements.txt` file or necessary python version info makes it a bit of a pain to setup a virtual environment.

I'm currently getting this when running `from pjuu.users import views`:

`ImportError: cannot import name 'Redis' from 'flask_redis' (/home/sigg3/python/pjuu/venv/lib/python3.9/site-packages/flask_redis/__init__.py)`

Seems to be a naming issue (should be FlaskRedis).

**Comment by docapotamus** [comment]
Hey @sigg3 we recently moved to Pipenv for dependency management.

You should be able to `pipenv install` and then `pipenv shell` and you will be in an automatically created virtual environment.

**Comment by sigg3** [comment]
Cheers @docapotamus !
