### ISSUE TITLE
Site is using an invalid security certificate

### ISSUE THREAD

**Issue by duritia** [pjuu/pjuu#409]
A few days ago, when I tried to refresh my open session in pjuu.com, the browser showed me this error:

![image](https://user-images.githubusercontent.com/69221194/183267659-fb1c63c2-1c6d-4412-8c39-b1d3c2668a45.png)

So, it seem there has been a few days since this started happening to all users. It should be easy to fix, I guess.

**Comment by mcrmonkey** [comment]
It had renewed in the background but nginx was being a bit of a pain to pickup the change. @docapotamus restarted it and it should be back to normal now.

Please could you re-check from your side to make sure you're seeing the same ?

**Comment by duritia** [comment]
Sure, @mcrmonkey ! I refreshed the page with error, now, and it worked. The other tabs I had open reloaded fine as well. So, everything seems back to normal.  (:

**Comment by mcrmonkey** [comment]
Thanks for raising and rechecking for us :heart:
