### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#46]
Allow users to lock down who can see there profile or any posts they post.

**Comment by pjuu** [comment]
Going to pick this up :smilecat:

The plan is to open profiles and posts to the world if a `public` flag is set on the post.

These should be selectable by the user when posting such as marking a post 'Public' will enable the world to see it on your profile and view it.

All replies to a public post will be public as it is the original poster who gets to decide. Also if replies could be Pjuu only then anyone viewing a post from outside may see a broken a conversation.

You will not be able to see a users followers, who they are following or anything else.

Their about message will be public so to will their score.

This is not going to turn in to a fine grained permissions system as I think the whole point of being social is that other users can see it. So to that extend their will only be two permissions:

Public: any one on the internet can view it. Profiles will be public by default.

Pjuu: members of the pjuu site will be able to see the post.

All posts which are currently on the site will NOT be marked public as to keep with the current permissions but I will add an endpoint which will allow for the toggling of this option.

**Comment by pjuu** [comment]
So uploads can be marked we need to also add a `public` key to them when they are uploaded. It will also need to be updated as the post is changed to public or not based on the presence of an `upload` field.

**Comment by pjuu** [comment]
Going to restyle the author boxes for posts and replies so I can add in the new public button. This will not be present on replies as its the post owner to decide if post is public.

**Comment by docapotamus** [comment]
Going to push this back to 0.10 as I think this needs some more thought. I don't know if opening up Pjuu is the correct thing to do.

**Comment by docapotamus** [comment]
@mcrmonkey I really like your idea of circles similar to Google+. This would be a lot more sane than trying to do it for users in a complex way. We need to come up with a good method to mix that with the followers model.

**Comment by docapotamus** [comment]
Going to start work on this over the weekend. The plan is now much simpler:

**Allow users to mark their profile as public.** This will allow non-Pjuu users to view their profile similar to a blog https://pjuu.com/joe for example would be viewable from anywhere and linkable to.

Permissions for replies will be based on the parent post. So if you comment on a post from a public user your comment will also be public. If you have opted not to be a public profile your posts themselves will not be affected.

###Terminology:
- **Post** A post which you authored that is not a reply to a previous post. These will have the permissions of your profile.
- **Reply/comment** A post which you made in response to some other/your own post. These will have the permissions of the parent post.

###Rationale
By having comments take on their parent posts permissions this allows the conversation to be able available to all the users the post was intended for. This should stop a strange history appearing of the conversation.

**Comment by docapotamus** [comment]
Closing superseded by #215.
