### ISSUE TITLE
Simplify URL schema

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#58]
Remove the complexity in the URLs. We should redesign them more a long the lines of a API.

For example:

`/<username>/<post_id>/<reply_id>/delete`

Gives semantic meaning to the URL in a way that is very convoluted. `reply_id` is a reply to `post_id` which was posted by `username`. That is a little silly. It may have made sense a year or two ago in my head but it no longer does.

There is also the case where:

`/<username>/<post_id>/delete`

Does the exact same job but with no reply context.

I do not know the correct schema but I will give it some thought over the next couple of days. It should be really simple to write and navigate manually.

There is also some issues with semantics from old stuff is still present within the URLs.

**Comment by pjuu** [comment]
`/i-has-alerts` isn't very pretty.

Will probably move to `/alerts/new` to return the same thing.

**Comment by Dudibob** [comment]
Looks great. Should help for SEO things as well.

**Comment by mcrmonkey** [comment]
probably worth sticking as close as you can to what the url is for
eg:
/alerts/check - check if there are new alerts for a user
/alerts/show - show users alerts (?)
or skip the /show part and if a user lands on /alerts it just shows the alerts. kind of a default action type thing

**Comment by pjuu** [comment]
@Dudibob didn't ever see your post. Please can you expand or join webRTC?

**Comment by pjuu** [comment]
At a like "check" but show is not needed as rest would suggest that /alerts/ is correct for a list of resources.

I know its not an API at this time but no reason to deviate.

**Comment by pjuu** [comment]
@mcrmonkey started the work on this. As discussed yesterday I've changed the alerts to 60 seconds and done it on a 200 OK, 404 NOT FOUND both should save idle bandwidth.

**Comment by docapotamus** [comment]
Their is just one thing to do on this and that is remove the `reply_id` laden URLs as this data can be gathered internally. A reply is a post!

Moving this to 0.10.

**Comment by docapotamus** [comment]
Closing this issue!

This is in progress and a lot of end points already have smaller URLs.

Rather than go back and change them all at one I will do this as and when needed. There are some other features in the pipeline that will change this.

I doubt this is affecting any users and has been here for a long, long time.
