### ISSUE TITLE
Test re-org

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#59]
The test suite repeats itself a lot.

We want 100% test coverage and great functional testing. This isn't that easy at the moment.

The test suite should be broken down a little without unnecessarily inflating the test count, it is probably far to low at the moment and we rely on Pythons exception handling a lot to point us to the issue rather than the test number.

After speaking to a friend at work we can also make the tests quicker with setUpClass() but we need to make the tests not so reliant on the database being clean between each case.

Will have a think and post a more detailed list of what we are to change and how we are to reorganise them.

**Comment by pjuu** [comment]
This can be done the same time as #46 

By sorting out the permissions a lot of the tests will need sorting.

**Comment by pjuu** [comment]
This isn't feasibly going to happen in 0.8 as it is a lot of work. Will place it on hold for the time being. I need a more details plan to the new layout of tests

**Comment by docapotamus** [comment]
This should be an ongoing effort to sort out the mess in the test suite. Closing this issue.
