### ISSUE TITLE
Issue labels

### ISSUE THREAD

**Issue by pjuu** [pjuu/pjuu#61]
These need sorting out as they are not very efficient.

**Comment by mcrmonkey** [comment]
I would suggest the following perhaps:

Priority's:
- High
- Normal
- Low
- Planned

Category's:
- Infrastructure
- Application
- Data Storage
- Security
- UI (User Interface)
- UX ( User Experience ) - meaning how stuff flows 
- Bug

**Comment by pjuu** [comment]
Looks good to me buddy. We can refine it as we add the labels to the current issues.

**Comment by pjuu** [comment]
I've added "Wont Fix" and "On Hold" to this list and implement them. Will classify what is here and what has been as a good test.

**Comment by pjuu** [comment]
I've classified all the current ones... do they make sense? Would you classify these differently?

**Comment by mcrmonkey** [comment]
looks okay to me that.
Although i would consider putting one of the priority tags on every issue. Mainly because my CDO says so. :)

**Comment by mcrmonkey** [comment]
also applied to infrastructure repo and issues there

**Comment by pjuu** [comment]
I agree and I thought I had. I used planned in most places because we don't have any issues.

**Comment by mcrmonkey** [comment]
Okies 
I'm going to close this because i think its done
