### ISSUE TITLE
Jessie for docker

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#62]
Convert the docker image to Jessie rather than Wheezy.

There are some issues with the required libraries that need to be tested.

**Comment by pjuu** [comment]
... Hold out on this.

**Comment by pjuu** [comment]
@mcrmonkey any change you can look in to this. Since I know you love Jessie and systemd :package:

**Comment by pjuu** [comment]
This is listed on the Debian package list for Jessie. https://packages.debian.org/jessie/python-pil

It says its the Pillow fork. In all honesty we could also do with a list for setting Pillow up on Debian, Ubuntu & CentOS latest versions. Will do some testing of running it on said systems and make a Wiki page for it.

**Comment by docapotamus** [comment]
@mcrmonkey the issue stopping this from installing has now been resolved as was a difference between development and prod. We can probably go ahead and add the Jessie docker image in.

We should also update the README to reflect Jessie as that should be used really.
