### ISSUE TITLE
Please add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [pjuu/pjuu#69]
A thread for is has been created at https://f-droid.org/forums/topic/pjuu/

**Comment by mcrmonkey** [comment]
Noted.

And thank you :)

For reference I'm the one operating the "pjuu" account at the moment on the forum.

**Comment by pizzamaker** [comment]
Added!

**Comment by pjuu** [comment]
Thanks @pizzamaker :)

**Comment by Mukt** [comment]
Thanks @pizzamaker for this suggestion!
I found Pjuu via f-droid.
