### ISSUE TITLE
Installation docs

### ISSUE THREAD

**Issue by deavmi** [pjuu/pjuu#72]
Will there be an easy installation script or some documentation on how to install **Pjuu*?

Thanks in advance. :smile:

**Comment by pjuu** [comment]
Hi :) I will try throw something together in the next day or so and will post it as a wiki. I'll try and outline how we have it deployed its relatively simple.

It will probably just be for Linux however as apart from a Macbook I don't own anything else :(

**Comment by deavmi** [comment]
That's awesome. I use GNU/Linux-libre, so hence that would be great.

Thanks :wink:

**Comment by pjuu** [comment]
Their is a guide in the README to getting running on your laptop it is for Debian Wheezy/Ubuntu (don't know versions of that to much).

**Comment by deavmi** [comment]
@pjuu okay. Thanks. :smile:

**Comment by pjuu** [comment]
@deavmi can you please point out what you need help setting up? I don't want to make them to generic if it is a specific issue.

**Comment by deavmi** [comment]
This issue can be closed, I have realized there is an installation script on the `README.md` file. Sorry.

**Comment by pjuu** [comment]
:)
