### ISSUE TITLE
More preferences

### ISSUE THREAD

**Issue by deavmi** [pjuu/pjuu#75]
I think it would be great for the user to have more settings in the settings area, such as:

- [ ] The ability to enable HTML refreshing at a certain interval for the suers' feed
- [ ] Ability to change your color scheme (basic themeing)

**Comment by pjuu** [comment]
Neither of these are going to be implemented any time soon to be honest. We have a lot more stuff we would like to implement before we worry to much about aesthetics at the like.

Will close this but will have it as reference.

**Comment by deavmi** [comment]
@deavmi Thanks
