### ISSUE TITLE
Pjuu's style of design

### ISSUE THREAD

**Issue by psgs** [pjuu/pjuu#78]
Hello!

My name's psgs, and I'm quite new to Pjuu. I was wondering, what sort of design or UI style should be implemented with Pjuu? Would a warm, colourful style be appropriate, or a calmer, relaxing, cooler style?

Many thanks,
psgs :palm_tree:

**Comment by pjuu** [comment]
Hi @psgs I'm not 100% sure as I'm not a designer :-P. The design is just done me making it work and not look as terrible. Feel free to do as you wish as long as its not crazy and has relative good browser support :-)

**Comment by psgs** [comment]
Hi @pjuu,

Thanks for your quick reply! I'll see if I can add a few things :smiley:

**Comment by pjuu** [comment]
That would be brilliant :-) please don't get offended if we don't instant pull something though. We are trying to keep things as simple as possible

**Comment by psgs** [comment]
That's fine :wink:
Simple is great.
