### ISSUE TITLE
Reverse votes/flags within time frame

### ISSUE THREAD

**Issue by docapotamus** [pjuu/pjuu#85]
Allow reversing a vote within a time frame.

This will mean if you vote wrong or vote by accident you can reverse the vote. So a +1/-1 can be changed to 0 by pressing the same vote again. This will should allow you to re-vote.

This how ever can be changed once the time frame from your last up/down vote has passed.

**Comment by pjuu** [comment]
Easiest way to achieve this is going to be store -/+ timestamp as the sorted set score on a vote rather than -1 or +1.

**Comment by pjuu** [comment]
@mcrmonkey this is a good one.

If you downvote someone with a user score of 0 then it does not apply the -1.

Then when it comes to undoing an upvote and your on a 0 score how should that be handled?
Also when you undo a downvote if they are on 0 should it apply a +1 as we don't know if the -1 was actually applied?

I have a few options which I want your advise on.

1. Remove minumum of 0 on a user.
2. Use another Redis key to decide if the post was applied?
3. Remove downvoting (much like like's on facebook)
4. Remove users scores so only posts can be voted on.

What's you opinion/questions?

**Comment by mcrmonkey** [comment]
If the user is on a zero score and a commenter removed their upvote it should knock it down to -1

From questions above:

1. what would the minimum for the user then be ?
2. "if the post was applied" - not sure i get what you mean here
3. i'm fine with the downvote thing tbh. whats the motivation for removing this ?
4. errm i dont mind this being there tbh. We could remove it though.
5. err what ?

**Comment by pjuu** [comment]
The vote applied means did it affect the post. For example if you pressed -1 the post would go to -1 but if the user was on 0 it would not go to -1. I though this would reduce bullying.

We could remove a users score and just have a post score or just allow users to go into negative.

If we decided to implement federation I don't know why any other sire would enforce a -1 however

**Comment by pjuu** [comment]
I love this idea but I am going to push it back to 0.10 as I think it is not critical at this point in time. It also gives me some time to work out a good solution.

**Comment by docapotamus** [comment]
I have a plan. We can keep it as it is but count a users post scores with MongoDB aggregation. If its < 0 then 0. This way I already have the solution coded up :)

**Comment by docapotamus** [comment]
Wow this has been a long time coming closed by #237
