### ISSUE TITLE
Pjuu's Login Page

### ISSUE THREAD

**Issue by psgs** [pjuu/pjuu#93]
Hello!

I have recently prototyped several new layouts for Pjuu's login page.
Which layout would work best with Pjuu? Is there anything that could be improved with either layout?

![First Login Page](https://cloud.githubusercontent.com/assets/3946887/8738907/74dce38a-2c78-11e5-82d1-2d86521e9d28.jpg)

---

![Second Login Page](https://cloud.githubusercontent.com/assets/3946887/8738917/7a3b76b6-2c78-11e5-9ded-5451442c22c7.jpg)

Thankyou,
psgs :palm_tree:

**Comment by pjuu** [comment]
:clap: wow they look amazing @psgs !!!

I really like the first one.

@mcrmonkey thoughts?

We may need to make the forgot password, reset password and signup forms follow a similar pattern so the entire auth system gets a lovely update

**Comment by pjuu** [comment]
We will need to stack the inputs on top of each other when scale in to mobile mode. We can create a another media-query so that we can have desktop, tablet and phone unlike now where tablets are treated as phones/desktops depending on size.

**Comment by psgs** [comment]
That sounds like a great idea :smiley:
